# Generated by Django 2.2.12 on 2020-04-19 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('F', 'F'), ('V', 'V')], max_length=1)),
            ],
            options={
                'db_table': 'food',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=255, unique=True)),
                ('has_died', models.BooleanField(default=False)),
                ('balance', models.CharField(default='0', max_length=100)),
                ('picture', models.CharField(blank=True, max_length=500)),
                ('age', models.IntegerField()),
                ('eye_color', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(max_length=500)),
                ('about', models.TextField(blank=True)),
                ('registered', models.DateTimeField()),
                ('tags', models.TextField(blank=True)),
                ('greeting', models.TextField(blank=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company', to='info_analytics.Company')),
                ('favourite_food', models.ManyToManyField(blank=True, db_table='people_food', related_name='food', to='info_analytics.Food')),
                ('friends', models.ManyToManyField(blank=True, db_table='people_friends', to='info_analytics.Person')),
            ],
            options={
                'db_table': 'people',
            },
        ),
    ]
